
//export MyComponent from './MyComponent/index.jsx'
export Header from './Header/index.jsx'
export Menus from './Menus/index.jsx'
export ButtonDemo from './Button/index.jsx'
export BadgeDemo from './Badge/index.jsx'
export ProgressBarDemo from './ProgressBar/index.jsx'
export LayoutDemo from './Layout/index.jsx'
export LoadingDemo from './Loading/index.jsx'
export TimelineDemo from './TimeLine/index.jsx'
export CalendarDemo from './Calendar/index.jsx'
export TableDemo from './Table/index.jsx'
export TreeDemo from './Tree/index.jsx'
export BreadCrumbDemo from './Breadcrumb/index.jsx'
export CheckboxDemo from './Checkbox/index.jsx'
export ModalDemo from './Modal/index.js'
export NotificationDemo from './Notification/index.js';
export PaginationDemo from './Pagination/index.js';
export MessageDemo from './Message/index.js';
export TooltipDemo from './Tooltip/index.js';
export PanelDemo from './Panel/index.js';
export TabDemo from './Tab/index.js';
export StepDemo from './Step/index.js';
export FormDemo from './Form/index';
export RateDemo from './Rate/index';
export CollapseDemo from './Collapse/index';
export IconDemo from './Icon/index';
export InputNumberDemo from './InputNumber/index';
export PopconfirmDemo from './Popconfirm/index';
export AlertDemo from './Alert/index';
export BackTopDemo from './BackTop/index';
export CascaderDemo from './Cascader/index';
export DropdownDemo from './Dropdown/index';
export ClipboardDemo from './Clipboard/index';
export TransferDemo from './Transfer/index';
export UploadDemo from './Upload/index';
export AutocompleteDemo from './Autocomplete/index';
export SliderDemo from './Slider/index';
//export DateDemo from './Datepicker';
//export DndDemo from './Dnd';
export TimeDemo from './Timepicker';
export LoadingStateDemo from './LoadingState';
export PopoverDemo from './Popover';
//export LocaleDemo from './Locale';
export CarouselDemo from './Carousel';
// export SelectDemo from './Select/index.js';
export RadioDemo from './Radio';
export SwitchDemo from './Switch';
export InputGroupDemo from './InputGroup';
export ColorPickerDemo from './ColorPicker';
export TagDemo from './Tag';
export SearchPanelDemo from './SearchPanel';
export AnchorDemo from './Anchor';
export TreeSelectDemo from './TreeSelect';
export PageLayoutDemo from './PageLayout';
export SvgIconDemo from './SvgIcon';